export const SUBMIT="SUBMIT"
export const DELETE="DELETE"
export const EDIT="EDIT"
export const SEARCH="SEARCH"
export const STATUS="STATUS"
export const DELETEMANY="DELETEMANY"


export const GET_USER_DATA="GET_USER_DATA"
export const SET_EDIT_DATA_AND_ACTION_TYPE="SET_EDIT_DATA_AND_ACTION_TYPE"


export const GET_POST_DATA="GET_POST_DATA"
export const GET_UID_POST_DATA="GET_UID_POST_DATA"
export const SET_POST_DATA_ADD="SET_POST_DATA_ADD"
export const SET_EDIT_DATA_ADD="SET_EDIT_DATA_ADD"



export const GET_RENDER_DATA="GET_RENDER_DATA"
export const DELETE_RENDER_DATA="DELETE_RENDER_DATA"
export const EDIT_RENDER_DATA="EDIT_RENDER_DATA"
export const STATUS_RENDER_DATA="STATUS_RENDER_DATA"
export const DELETE_MANY_RENDER_DATA="DELETE_MANY_RENDER_DATA"
export const DELETE_MULTY_RENDER_DATA="DELETE_MULTY_RENDER_DATA"



export const STEP_GET_DATA="STEP_GET_DATA"
export const STEP_DELETE_DATA="STEP_DELETE_DATA"
export const STEP_EDIT_DATA="STEP_EDIT_DATA"
export const STEP_STATUS_DATA="STEP_STATUS_DATA"
export const STEP_SELECT_MANY_DATA="STEP_SELECT_MANY_DATA"
export const STEP_DELETE_MULTI_DATA="STEP_DELETE_MULTI_DATA"